### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.storage' not always reproducable

### ISSUE THREAD

**Issue by smetj** [Azure/azure-storage-python#438] opened 2018-03-18 11:46 UTC
### Which service(blob, file, queue) does this issue concern?

queue (possibly others?)

### What problem was encountered?
Installing `azure-storage-queue` (in a clean virtualenv) frequently (so not always) leads to a module installation which cannot be imported.
The installation steps followed are the ones documented in https://docs.microsoft.com/en-us/azure/storage/queues/storage-python-how-to-use-queue-storage 

_In a fresh Python-3.6.3 virtualenv_

```
$ pip install azure-storage-queue
... installation happens successfully, no errors ...
$  python -c 'from azure.storage.queue import QueueService'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.storage'

```
Sometimes the installation does result into a module which can be imported without errors but most often, ... it does not.

### Have you found a mitigation/solution?
A mitigation yes

`$ pip install azure-storage-queue --upgrade --force-reinstall
`
Fixes the problem. 
Keep in mind that the installation is done on a clean virtualenv.

I'd expect the import to succeed without any further ado after installing `azure-storage-queue`.
If specific details are required, pls let me know.

Tnx,

Jelle

**Comment by zezha-msft** [comment] 2018-03-19 21:04
Hi @smetj, thanks for reaching out!

I have seen a few others mentioning a similar issue, but I have not been able to reproduce it myself. Could you please provide me a snapshot of your 'pip freeze' when the import does not work? And which python distribution are you using? On which OS? Thanks!

**Comment by zezha-msft** [comment] 2018-04-24 21:26
Hi @smetj, I'm closing this for now as I have not received more information from you. Please do let me know if you are still encountering problems with importing the module. Thanks!

**Closed by zezha-msft** 2018-04-24 21:26 UTC

**Comment by tomwwagstaff-product** [comment] 2018-08-28 14:44
Having exactly this problem after `conda install azure`.

**Comment by zezha-msft** [comment] 2018-08-28 17:57
Hi @tomwwagstaff-product, thanks for reaching out! 

Is this problem always reproducible? Could you please post your `pip freeze`?

**Comment by tomwwagstaff-product** [comment] 2018-08-29 09:05
Hey @zezha-msft,
Thanks for getting back to me, but no worries - I removed the package and then pip installed it - as advised here: https://github.com/Azure/azure-storage-python/issues/262 - and it's now loading correctly.

**Comment by zezha-msft** [comment] 2018-08-29 18:52
@tomwwagstaff-product  Ok sounds good!

**Comment by svangeti** [comment] 2019-12-06 05:07
@tomwwagstaff-product / @zezha-msft  - It looks like azure-storage-blob packages are not working with python version 3.7. I am trying to deploy the azure function using python3.7 but always getting `ModuleNotFoundError: No module named 'azure.storage'`. the same setup works with python3.6 version

**Comment by zezha-msft** [comment] 2019-12-06 21:54
Hi @svangeti, could you please clarify which version of the SDK are you installing? 

Python 3.7 is covered in our tests so most likely this is something caused by Azure Functions.

**Comment by svangeti** [comment] 2019-12-09 14:43
> Hi @svangeti, could you please clarify which version of the SDK are you installing?
> 
> Python 3.7 is covered in our tests so most likely this is something caused by Azure Functions.

Hi @zezha-msft  - the pip install automatically installing this version `azure-storage-blob==12.1.0`
. I don't even have azure-storage package reference anywhere, but it's complaining with above error on 3.7 runtime. I tried installing `azure-storage==0.36.0` package as well but of no use.

**Comment by Alababdiy** [comment] 2019-12-13 20:34
same problem here 
is running or local 
but when i deployment in azure app is got 
:( Application Error
from azure.storage.blob import BlobClient
2019-12-13T20:26:54.480506472Z ModuleNotFoundError: No module named 'azure'

**Comment by nccurry** [comment] 2020-01-23 17:47
Seeing this problem when doing the following in ansible:
```
- name: Install role dependencies
  pip:
    name:
    - azure
    - packaging
    extra_args: --user
```
and trying to use azure_rm_* ansible modules.

**Comment by ppakawatk** [comment] 2020-02-05 08:02
> > Hi @svangeti, could you please clarify which version of the SDK are you installing?
> > Python 3.7 is covered in our tests so most likely this is something caused by Azure Functions.
> 
> Hi @zezha-msft - the pip install automatically installing this version `azure-storage-blob==12.1.0`
> . I don't even have azure-storage package reference anywhere, but it's complaining with above error on 3.7 runtime. I tried installing `azure-storage==0.36.0` package as well but of no use.

Is there anyone found the solution for this? 
I am facing the exactly same problem with @svangeti

**Comment by anilvemula0** [comment] 2020-03-12 11:07
> @tomwwagstaff-product / @zezha-msft - It looks like azure-storage-blob packages are not working with python version 3.7. I am trying to deploy the azure function using python3.7 but always getting `ModuleNotFoundError: No module named 'azure.storage'`. the same setup works with python3.6 version

This answer helped me. There is a lot of confusion around azure.storage packages.

**Comment by chinwobble** [comment] 2020-07-23 03:20
@zezha-msft I'm using Python 3.6.10 with azure-storage-blob 12.3.0 and 12.3.2 and they both aren't working

**Comment by CoenraadS** [comment] 2020-08-04 13:40
I am having the same issue.

Using a python 3.7 dev container, as clean as an environment I can get.

Python 3.7.8

```
azure-core==1.7.0
azure-storage-blob==12.3.2
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
cryptography==3.0
idna==2.10
isodate==0.6.0
msrest==0.6.18
oauthlib==3.1.0
pycparser==2.20
requests==2.24.0
requests-oauthlib==1.3.0
six==1.15.0
urllib3==1.25.10
```
