### ISSUE TITLE
Can't insert entity with chinese string property

### ISSUE THREAD

**Issue by erinus** [Azure/azure-storage-python#91] opened 2015-12-26 20:02 UTC
[1] If I use the codes. it gets error response.
Code:
entity = azure.storage.table.Entity()
entity.SiteCode = '232633627068'
entity.SiteName = azure.storage.table.EntityProperty('Edm.String', '蘋果新聞'.encode('utf-16'))
table.insert_entity('sites', entity)

Response:
azure.common.AzureHttpError: Bad Request
<?xml version="1.0" encoding="utf-8"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code>InvalidInput</code><message xml:lang="en-US">One of the request inputs is not valid.
RequestId:b87b16db-0002-004b-4b15-40a58e000000
Time:2015-12-26T19:44:59.4595166Z</message></error>

[2] If I use the codes. it gets success response.
Code:
entity = azure.storage.table.Entity()
entity.SiteCode = '232633627068'
table.insert_entity('sites', entity)

**Comment by emgerner-msft** [comment] 2016-01-04 19:57
I am not able to reproduce this with Python 3.4 and fully up to date dependencies. What version of Python are you using so I can try with a more similar setup? 

Note: If you check out the [test_unicode_property_value](https://github.com/Azure/azure-storage-python/blob/master/tests/test_storage_table.py#L1284) unit test, you'll see that directly inserting unicode with no encoding should work. Could you try something similar to this code?

**Comment by jehine-MSFT** [comment] 2016-02-16 23:36
Closing as we were not able to repro this issue. Please reopen if you can provide us with a more detailed repro.

Thanks!

**Closed by jehine-MSFT** 2016-02-16 23:36 UTC
