### ISSUE TITLE
Content-type not getting set

### ISSUE THREAD

**Issue by mmenajr** [Azure/azure-storage-python#441] opened 2018-03-26 23:42 UTC
### Which service(blob, file, queue) does this issue concern?
Blob. Specifically the BlockBlobService

### What problem was encountered?
Setting the content-type when creating a file appears to be getting ignored. Also, trying to update them using set_blob_properties just removes that header.

When initially uploading files, I am able to use mimetypes to get the type of file and create a ContentSettings object that I then pass to upload_from_path. This seems to ignore it as the content-type in Azure shows the default application/octet-stream.

When I call the set_blob_properties and try to set the content-type it seems to just remove the header completely instead of updating it.

### Have you found a mitigation/solution?
Currently removing the header allows the files to work as intended but would like to be able to dynamically set them as needed.

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment] 2018-04-10 09:13
Hi @mmenajr, I was not able to reproduce your problem (I validated that the content-type was being set properly in both cases with the help of Storage Explorer). Could you please take a look at the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L100) and see if you can spot any problem in your script? Thanks.

I'll close this for now as it doesn't seem to be a bug in the SDK. Please let me know if you still have trouble with this issue.

**Closed by zezha-msft** 2018-04-10 09:13 UTC

**Comment by mmenajr** [comment] 2018-04-12 17:09
@zezha-msft I am still seeing the issue even after looking at the sample and performing the workflow in a similar manner. I have attached an image of my code in debug mode showing the values. Below is a breakdown of each variable:
**file_type** = uses mimetype to get the file type
**blob** = first call to get the properties of a blob that I uploaded a few lines above (upload not shown)
**content_type** = shows that the content type is the default as I did not pass any during upload.
**file_content_settings** = ContentSettings object that I am going to pass to update the blob
**ct** = showing that the file_content_settings did pick up the correct value to content_type
**blob2** = second call to get blob properties. Using a new call to ensure no issues.
**content_type2** = shows that after the update, the content_type for the blob is empty.
![snippet](https://user-images.githubusercontent.com/37817221/38692739-998031d0-3e39-11e8-8b8e-5d3607153206.JPG)

**Comment by mmenajr** [comment] 2018-04-12 22:37
@zezha-msft Please ignore for now. Seems that my GUI based script is not working but my console based one is. Going to try to troubleshoot on my end. Thanks.

**Comment by zezha-msft** [comment] 2018-04-12 22:40
Hi @mmenajr, OK! Please keep me updated.
