### ISSUE TITLE
Failure to upload large file (>200GB)

### ISSUE THREAD

**Issue by thanhnhut90** [Azure/azure-storage-python#346] opened 2017-09-06 18:41 UTC
Hi guys, 

I have been having issue with uploading large file (>200GB) with the library. According to the [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs), with the REST API version after 2016-05-31, the size limit can be up to 4.75TB (100 MB chunk x 50000 blocks). 
I have been playing with the chunk size limit (default is 4MB). When I changed the MAX_BLOCK_SIZE to be larger than 10MB, i saw ReadTimeout
`AzureException: ReadTimeout: HTTPSConnectionPool(host='host.blob.core.windows.net', port=443): Read timed out. (read timeout=20)`
When the block size was 10MB and `validate_content=True`, I got md5 mismatched 
`AzureHttpError: The MD5 value specified in the request did not match with the MD5 value calculated by the server.`
When I kept the block size the same (10MB) and disable md5 check, the file got uploaded successfully (263GB). I downloaded the file down and manually performed md5sum on the whole file, the md5 matched with the file on local drive. 
I updated the library version to 0.36.0, but it didn't make any difference. 

Could you please take a look if this is a bug/service limit, or if I did not do it correctly?

Thanks

**Comment by zezha-msft** [comment] 2017-09-06 20:33
Hi @thanhnhut90, thank you for bring this to our attention!

Concerning the ReadTimeout, I would suggest to increase the socket_timeout (in BlockBlobService's constructor) to higher than 20 seconds, and see if that helps with your situation. 

And for the MD5 mismatch, I will try to reproduce your issue, and update there. 😃

**Comment by zezha-msft** [comment] 2017-09-06 21:43
@thanhnhut90 I was able to reproduce this problem. I have added this to our backlog. Thank you for reporting it! 👍

**Comment by thanhnhut90** [comment] 2017-09-10 05:05
thanks @zezha-msft. Regarding changing the timeout, the result is hit or miss. I tried to change the timeout to 60 and 120 seconds.
For 60 seconds timeout and 20 MB chunk, I was able to upload a file around 200GB; however, it took  longer period of time. Previously, I was able to upload 263GB in around 2 hours and 20 mins. For 60s timeout, it took 3.75 hours to upload a file around 203GB.
When I tried to upload a 700GB file with 20 MB and 60s then 120s timeout, it failed both times.

**Comment by zezha-msft** [comment] 2017-10-31 21:21
Hi @thanhnhut90, I have fixed the transactional MD5 problem and it will go out with the next blob package release. 

As for the timeout problem, I would suggest to increase the number of allowed retries by doing this on the BlockBlobService object:

```python
service.retry = ExponentialRetry(max_attempts=10).retry
```

The socket_timeout governs the delay between packets arriving on the socket. It is possible that your network is unstable, and due to the sheer number of requests while uploading big files, the delay becomes too long and the timeout gets triggered very often. Increasing the max number of retries could potentially help your situation, since the default number of retries is only 3.

Please let me know if you have more questions. Unfortunately for the moment you'll have to tweak the retry policy, block size, and socket timeout until a sweet spot is found. We are working on something to improve this situation. Thanks!

**Comment by zezha-msft** [comment] 2017-11-03 21:06
@thanhnhut90 This was fixed in azure-storage-blob v0.37.1. Please let me know if you encounter any other problem. :)

**Closed by zezha-msft** 2017-11-03 21:06 UTC
Labels: bug
