### ISSUE TITLE
Getting a "Failed to parse headers" warning when using the TableService

### ISSUE THREAD

**Issue by smuelas** [Azure/azure-storage-python#167] opened 2016-04-27 12:50 UTC
I am using the azure-storage-python library for inserting into an Azure Table some json data from a flask server method. Concretely, I am calling the insert_entity method of the batch method of  a TableService object. 

Whenever I make the call, the following warning message gets generated in the server log: 

"Failed to parse headers (url=https://ourdomainstoragename.table.core.windows.net:443/$batch): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
    Traceback (most recent call last):
      File "/somepath/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 390, in _make_request
        assert_header_parsing(httplib_response.msg)
      File "/somepath/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/response.py", line 59, in assert_header_parsing
        raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
    requests.packages.urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''

I am using the following packages/binaries: python version 3.4.3, Flask=0.10.1 azure-storage-python 0.31.0 installed in a Ubuntu 15.10

**Comment by emgerner-msft** [comment] 2016-04-27 16:30
Could you please show how you're constructing the batch and calling insert_entity? We have [tests](https://github.com/Azure/azure-storage-python/blob/master/tests/test_table_batch.py) and [samples](https://github.com/Azure/azure-storage-python/blob/master/samples/table/table_usage.py#L174) which insert an entity using a batch, so while it's quite possible you've found an issue we need repro code in order to track down what that is.

**Comment by smuelas** [comment] 2016-04-28 11:50
Yes, no problem, here is the code  that I am using. If it helps, I am using it inside a flask server so the method is called by flask whenever the corresponding HTTP call is received. 
```python
    table_service = TableService(account_name=AZ_AN,  account_key=AZ_KY)
    table_service.create_table(AZ_TABLENAME)

    # actions_data is an array of dict objects
    with table_service.batch(AZ_TABLENAME) as batch:
        for action_datum in actions_data:
            action_datum['PartitionKey'] = AZ_TABLE_PARTKEY
            action_datum['RowKey'] = str(uuid.uuid4())
            batch.insert_entity(action_datum)```

**Comment by emgerner-msft** [comment] 2016-04-28 16:56
Doesn't matter to me how the code is called (flask or otherwise), just how it runs. I don't see anything abnormal here, but I also can't see what's in action_datum so it's hard for me to tell if everything in it is valid. Is it just all strings or what? If I run this on my box with the same version of Python with a dict of regular strings this works just fine:

```
        actions_data = [{'foo': 'bar'}, {'boo': 'baz'}]
        with table_service.batch(table_name) as batch:
            for action_datum in actions_data:
                action_datum['PartitionKey'] = '001'
                action_datum['RowKey'] = str(uuid.uuid4())
                batch.insert_entity(action_datum)
```

I need all of the the code I can use to reproduce the problem, or a network trace that shows the problem (using something like Fiddler or Wireshark).

**Comment by smuelas** [comment] 2016-05-02 17:24
action_datum is a simple dict of strings. To make it easier I have written a simple standalone version of the program that launches the same warning message. As you can see, you need to have a log handler registered in order to capture the warning message.

```python
AZ_AN = # corresponding azure account name
AZ_KY = # corresponding azure account key
AZ_TABLENAME = 'testingTable'
AZ_TABLE_PARTKEY = 'testing'

logging.getLogger().addHandler(logging.StreamHandler())

table_service = TableService(AZ_AN, AZ_KY)
table_service.create_table(AZ_TABLENAME)

data = res = [ {'key1' : 'value1' , 'key2' : 'value2'}, {'key3' : 'value3', 'key4' : 'value4'}]

with table_service.batch(AZ_TABLENAME) as batch:
    for datum in data:
        datum['PartitionKey'] = AZ_TABLE_PARTKEY
        datum['RowKey'] = str(uuid.uuid4())
        batch.insert_entity(datum)
```

**Comment by emgerner-msft** [comment] 2016-05-02 17:32
I can look further into why urllib adds a warning log, but just to confirm: This runs perfectly fine, correct?

**Comment by emgerner-msft** [comment] 2016-05-02 17:39
FYI: [This](https://github.com/shazow/urllib3/issues/800) looks like it's probably it, if you tell me this indeed runs just fine for you.

**Comment by smuelas** [comment] 2016-05-02 17:45
Yes, everything runs fine and the insertions in the table are performed correctly. Thanks for the info and  the link, it seems that it is the same issue

**Comment by emgerner-msft** [comment] 2016-05-02 17:55
Okay, good to hear. I'll close this then and tracking can be done on the root issue in urllib3.

**Closed by emgerner-msft** 2016-05-02 17:55 UTC

**Comment by AbdolrezaMadi** [comment] 2020-05-18 16:55
Hello,

The discussion is describing the root cause, however there is no explanation on how to suppress it. Any suggestion?

Thanks,
